" set the tabsizes
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

" syntax highlighting
syntax on

" line numbering
set number

" highlight colomn 110
set colorcolumn=110
highlight ColorColumn ctermbg=darkgray

" Vundle setup
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'Valloric/YouCompleteMe'
Plugin 'majutsushi/tagbar'
Plugin 'vim-scripts/ctags.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


" mappings
nmap <F8> :TagbarToggle<CR>

" integrate YouCompleteMe
let g:ycm_extra_conf_globlist = ['~/.vim/.ycm_extra_conf.py']
